version: '3'

networks:
  public:

volumes:
  rabbitmq_data:
    driver: local
  db_data:
    driver: local


services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/bitnami
    ports:
      - 15672:15672
    networks:
      - public
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped
  
  mySQL:
    image: mysql:8
    command: --init-file /data/application/init.sql
    container_name: mySQL
    networks:
      - public
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=Tags
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    ports:
      - 3306:3306

  tags:
    build: .
    container_name: tags
    depends_on:
      - mySQL
      - rabbitmq
    networks:
      - public
    ports:
      - 8080:80
      - 5001:5000
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - AMQP_URI=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:5672
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    