version: '3'

networks:
  public:
  rabbit-network:
    external:
      name: webgateway_rabbit-network


volumes:
  rabbitmq_data:
    driver: local
  db_data:
    driver: local


services:
  
  mySQL:
    image: mysql:8
    command: --init-file /data/application/init.sql
    container_name: mySQL
    networks:
      - public
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=Tags
    ports:
      - 3306:3306

  tags:
    build: .
    container_name: tags
    depends_on:
      - mySQL
    networks:
      - rabbit-network
      - public
    ports:
      - 8080:80
      - 5001:5000
    environment:
      - AMQP_USER=${RABBITMQ_USERNAME}
      - AMQP_PASS=${RABBITMQ_PASSWORD}
      - AMQP_URI=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    